package io.akka.deepwiki.application;

import io.akka.deepwiki.domain.WikiTaskRequest;

/**
 * SPEC-001 §4.1: deterministic stand-in for the language-model boundary. Not a real LLM —
 * it returns a fixed, minimal-but-valid wiki-structure XML for a structure prompt (detected
 * the same way the source's own test suite detects it: presence of {@code <file_tree>}), and
 * a fixed citation-bearing Markdown body for a page prompt, so the orchestration, parsing,
 * and citation-resolution logic downstream of "the model responded" has real input to run
 * against without calling a real provider.
 */
public final class StubContentGenerationClient implements ContentGenerationClient {

  @Override
  public String generate(WikiTaskRequest request, String prompt) {
    if (prompt.contains("<file_tree>")) {
      return """
          <wiki_structure>
            <title>Overview</title>
            <description>Generated by the stub content client.</description>
            <pages>
              <page id="page-1">
                <title>Getting Started</title>
                <importance>high</importance>
                <relevant_files><file_path>README.md</file_path></relevant_files>
              </page>
            </pages>
          </wiki_structure>
          """;
    }
    return "# Getting Started\n\nSee [README.md:1]() for details.\n";
  }
}
